### ISSUE TITLE
Input data to convert binary mask to JSON

### ISSUE THREAD

**Issue by AISoltani** [brunobelloni/binary-to-coco-json-converter#1]
Hi, We have labeled images whose labels are in binary mask in separate folder per images, how can I import the data so that I can get JSON output from it, I want this JSON to convert to Yolo format?

**Comment by donjuanpond** [comment]
I'm having the same issue, is there any solution?

**Comment by brunobelloni** [comment]
Can you describe a little about your dataset?

this repository is working with [this](https://github.com/brunobelloni/binary-to-coco-json-converter/tree/master/dataset) folder structure:
- test_mask
- - classe_a
- - - image_a1
- - - image_a2
- - - ...
- - classe_b
- train_mask
- - classe_a
- - classe_b
- val_mask
- - classe_a
- - classe_b

**Comment by donjuanpond** [comment]
Hey there, I ended up just using the repo you linked to (https://github.com/chrise96/image-to-coco-json-converter) and uploading the images under the train and train_mask subfolders in the dataset folder. I had to do some modification to the code to get it to work (such as copying code from the jupyter notebook to a .py file because of some package issues and modifying the code itself to avoid errors with MultiPolygons). Thanks for responding so quickly, though!
